chore: add Cypress tests to Navigation plugin
kaltura/playkit-js-navigation pull request #296
Opened 2023-02-02 14:51 UTC by semarche-kaltura

1. clean-up `package.json` from unused dependencies;
2. add and configure cypress test library;
3. add e2e tests:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/51074448/216356371-ff76fd0d-1585-475a-bb2d-79b6eab361d6.png">

https://user-images.githubusercontent.com/51074448/216356613-84ed177e-700c-400a-b70f-daf8be13acb8.mp4

2023-02-02 15:24 UTC, SivanA-Kaltura requested changes
@semarche-kaltura  
looks good
my only concern is about including binary files as they can increase the repository size on every commit:
https://stackoverflow.com/a/52326938

2023-02-02 16:47 UTC, semarche-kaltura commented
> @semarche-kaltura looks good my only concern is about including binary files as they can increase the repository size on every commit: https://stackoverflow.com/a/52326938

size of media (binary files) - 4,4 MB and they're  not gonna be changed, so we ok with it.

2023-02-05 09:18 UTC, SivanA-Kaltura approved these changes

2023-02-06 15:20 UTC, lianbenjamin approved these changes

2023-02-06 15:21 UTC, merged